spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      #dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
  datasource:
    url: jdbc:mysql://localhost:3306/red_cross_surveys?serverTimezone=UTC
    username: root
    password: admin1234
    driverClassName: com.mysql.cj.jdbc.Driver